/**
 * GENERATED FILE — do not edit by hand.
 *
 * MLS PIN coded-field labels, from https://h3o.mlspin.com/tools/idx/idxDownloads/field_reference.asp
 * (public, unlike the listing feeds themselves).
 *
 * Shape: field -> property type -> code -> label. The property type is NOT
 * optional: HEATING "C" is "Gas" on a rental, "Hot Air Gravity" on a
 * single-family and "Hot Water Baseboard" on a condo.
 *
 * Regenerate with: node scripts/generate-idx-codes.mjs
 * Last generated: 2026-09-01
 */

export type IdxPropType = 'SF' | 'CC' | 'MF' | 'RN';

export const IDX_CODES: Record<
  string,
  Partial<Record<IdxPropType, Record<string, string>>>
> = {
  "APPLIANCES": {
    "CC": {
      "1": "Cooktop - ENERGY STAR",
      "2": "Range - ENERGY STAR",
      "3": "Water Instant Hot",
      "4": "Rangetop - ENERGY STAR",
      "5": "Oven - ENERGY STAR",
      "A": "Range",
      "B": "Wall Oven",
      "C": "Dishwasher",
      "D": "Disposal",
      "E": "Compactor",
      "F": "Microwave",
      "G": "Indoor Grill",
      "H": "Countertop Range",
      "I": "Refrigerator",
      "J": "Freezer",
      "K": "Washer",
      "L": "Dryer",
      "M": "Water Treatment",
      "N": "Other (See Remarks)",
      "O": "None",
      "P": "Refrigerator - ENERGY STAR",
      "Q": "Refrigerator - Wine Storage",
      "R": "Dryer - ENERGY STAR",
      "S": "Dishwasher - ENERGY STAR",
      "T": "Washer - ENERGY STAR",
      "U": "Freezer - Upright",
      "V": "Washer / Dryer Combo",
      "W": "Vacuum System",
      "X": "Vacuum System - Rough-in",
      "Y": "Vent Hood",
      "Z": "Water Softener"
    },
    "MF": {
      "1": "Cooktop - ENERGY STAR",
      "2": "Range - ENERGY STAR",
      "3": "Water Instant Hot",
      "4": "Rangetop - ENERGY STAR",
      "5": "Oven - ENERGY STAR",
      "6": "Washer Hookup",
      "7": "Dryer Hookup",
      "8": "Washer & Dryer Hookup",
      "A": "Range",
      "B": "Wall Oven",
      "C": "Dishwasher",
      "D": "Disposal",
      "E": "Compactor",
      "F": "Microwave",
      "G": "Indoor Grill",
      "H": "Countertop Range",
      "I": "Refrigerator",
      "J": "Freezer",
      "K": "Washer",
      "L": "Dryer",
      "M": "Water Treatment",
      "N": "Other (See Remarks)",
      "O": "None",
      "P": "Refrigerator - ENERGY STAR",
      "Q": "Refrigerator - Wine Storage",
      "R": "Dryer - ENERGY STAR",
      "S": "Dishwasher - ENERGY STAR",
      "T": "Washer - ENERGY STAR",
      "U": "Freezer - Upright",
      "V": "Washer / Dryer Combo",
      "W": "Vacuum System",
      "X": "Vacuum System - Rough-in",
      "Y": "Vent Hood",
      "Z": "Water Softener"
    },
    "RN": {
      "1": "Cooktop - ENERGY STAR",
      "2": "Range - ENERGY STAR",
      "3": "Water Instant Hot",
      "4": "Rangetop - ENERGY STAR",
      "5": "Oven - ENERGY STAR",
      "A": "Range",
      "B": "Wall Oven",
      "C": "Dishwasher",
      "D": "Disposal",
      "E": "Compactor",
      "F": "Microwave",
      "G": "Indoor Grill",
      "H": "Countertop Range",
      "I": "Refrigerator",
      "J": "Freezer",
      "K": "Washer",
      "L": "Dryer",
      "M": "Water Treatment",
      "N": "Other (See Remarks)",
      "O": "None",
      "P": "Refrigerator - ENERGY STAR",
      "Q": "Refrigerator - Wine Storage",
      "R": "Dryer - ENERGY STAR",
      "S": "Dishwasher - ENERGY STAR",
      "T": "Washer - ENERGY STAR",
      "U": "Freezer - Upright",
      "V": "Washer / Dryer Combo",
      "W": "Vacuum System",
      "X": "Vacuum System - Rough-in",
      "Y": "Vent Hood",
      "Z": "Water Softener"
    },
    "SF": {
      "1": "Cooktop - ENERGY STAR",
      "2": "Range - ENERGY STAR",
      "3": "Water Instant Hot",
      "4": "Rangetop - ENERGY STAR",
      "5": "Oven - ENERGY STAR",
      "A": "Range",
      "B": "Wall Oven",
      "C": "Dishwasher",
      "D": "Disposal",
      "E": "Compactor",
      "F": "Microwave",
      "G": "Indoor Grill",
      "H": "Countertop Range",
      "I": "Refrigerator",
      "J": "Freezer",
      "K": "Washer",
      "L": "Dryer",
      "M": "Water Treatment",
      "N": "Other (See Remarks)",
      "O": "None",
      "P": "Refrigerator - ENERGY STAR",
      "Q": "Refrigerator - Wine Storage",
      "R": "Dryer - ENERGY STAR",
      "S": "Dishwasher - ENERGY STAR",
      "T": "Washer - ENERGY STAR",
      "U": "Freezer - Upright",
      "V": "Washer / Dryer Combo",
      "W": "Vacuum System",
      "X": "Vacuum System - Rough-in",
      "Y": "Vent Hood",
      "Z": "Water Softener"
    }
  },
  "BASEMENT_FEATURE": {
    "CC": {
      "A": "Full",
      "B": "Partial",
      "C": "Crawl",
      "D": "Finished",
      "E": "Partially Finished",
      "F": "Walk Out",
      "G": "Interior Access",
      "H": "Garage Access",
      "I": "Bulkhead",
      "J": "Sump Pump",
      "K": "Radon Remediation System",
      "L": "Dirt Floor",
      "M": "Concrete Floor",
      "N": "Slab",
      "Q": "Unfinished Basement",
      "R": "Exterior Access"
    },
    "MF": {
      "A": "Full",
      "B": "Partial",
      "C": "Crawl",
      "D": "Finished",
      "E": "Partially Finished",
      "F": "Walk Out",
      "G": "Interior Access",
      "H": "Garage Access",
      "I": "Bulkhead",
      "J": "Sump Pump",
      "K": "Radon Remediation System",
      "L": "Dirt Floor",
      "M": "Concrete Floor",
      "N": "Slab",
      "Q": "Unfinished Basement",
      "R": "Exterior Access"
    },
    "RN": {
      "A": "Full",
      "B": "Partial",
      "C": "Crawl",
      "D": "Finished",
      "E": "Partially Finished",
      "G": "Interior Access",
      "H": "Garage Access",
      "I": "Bulkhead",
      "K": "Radon Remediation System",
      "L": "Dirt Floor",
      "M": "Concrete Floor",
      "N": "Slab",
      "Q": "Unfinished Basement",
      "R": "Exterior Access"
    },
    "SF": {
      "A": "Full",
      "B": "Partial",
      "C": "Crawl",
      "D": "Finished",
      "E": "Partially Finished",
      "F": "Walk Out",
      "G": "Interior Access",
      "H": "Garage Access",
      "I": "Bulkhead",
      "J": "Sump Pump",
      "K": "Radon Remediation System",
      "L": "Dirt Floor",
      "M": "Concrete Floor",
      "N": "Slab",
      "Q": "Unfinished Basement",
      "R": "Exterior Access"
    }
  },
  "CC_TYPE": {
    "CC": {
      "A": "Condo",
      "B": "Co-op",
      "C": "Condex"
    }
  },
  "CONSTRUCTION": {
    "CC": {
      "A": "Frame",
      "B": "Brick",
      "C": "Stone/Concrete",
      "D": "Block",
      "E": "Log",
      "F": "Modular",
      "G": "Post & Beam",
      "H": "Other (See Remarks)",
      "I": "Adobe",
      "J": "Aerated Autoclaved Concrete",
      "K": "Barn board",
      "L": "Cob",
      "M": "Conventional (2x4-2x6)",
      "N": "Cork",
      "O": "Earthship",
      "P": "Other / Hybrid",
      "Q": "Rammed Earth",
      "R": "Reuse / Exchange",
      "S": "Straw bale",
      "T": "Timber Frame",
      "U": "Vertical Siding",
      "V": "Cement Board",
      "W": "Structural Insulated Panels",
      "X": "Double Stud Wall"
    },
    "MF": {
      "A": "Frame",
      "B": "Brick",
      "C": "Stone/Concrete",
      "D": "Block",
      "E": "Log",
      "F": "Modular",
      "G": "Post & Beam",
      "H": "Other (See Remarks)",
      "I": "Adobe",
      "J": "Aerated Autoclaved Concrete",
      "K": "Barn board",
      "L": "Cob",
      "M": "Conventional (2x4-2x6)",
      "N": "Cork",
      "O": "Earthship",
      "P": "Other / Hybrid",
      "Q": "Rammed Earth",
      "R": "Reuse / Exchange",
      "S": "Straw bale",
      "T": "Timber Frame",
      "U": "Vertical Siding",
      "V": "Cement Board"
    },
    "SF": {
      "A": "Frame",
      "B": "Brick",
      "C": "Stone/Concrete",
      "D": "Block",
      "E": "Log",
      "F": "Modular",
      "G": "Post & Beam",
      "H": "Other (See Remarks)",
      "I": "Adobe",
      "J": "Aerated Autoclaved Concrete",
      "K": "Barn board",
      "L": "Cob",
      "M": "Conventional (2x4-2x6)",
      "N": "Cork",
      "O": "Earthship",
      "P": "Other / Hybrid",
      "Q": "Rammed Earth",
      "R": "Reuse / Exchange",
      "S": "Straw bale",
      "T": "Timber Frame",
      "U": "Vertical Siding",
      "V": "Cement Board",
      "W": "Structural Insulated Panels",
      "X": "Double Stud Wall"
    }
  },
  "COOLING": {
    "CC": {
      "A": "Central Air",
      "B": "Window AC",
      "C": "Wall AC",
      "D": "Heat Pump",
      "E": "2 Units",
      "F": "3 or More",
      "G": "Common",
      "H": "Individual",
      "I": "Unit Control",
      "J": "Fan Coil",
      "K": "Other (See Remarks)",
      "L": "None",
      "M": "Active Solar",
      "N": "Geothermal Heat Pump",
      "O": "High Seer Heat Pump (12+)",
      "P": "Overhangs Abv South Facing Windows",
      "Q": "Passive Cooling",
      "R": "Swamp Cooler (Evaporative)",
      "S": "Wind",
      "T": "ENERGY STAR",
      "U": "Air Source Heat Pumps (ASHP)",
      "V": "Ductless Mini-Split System"
    },
    "MF": {
      "A": "Central Air",
      "B": "Window AC",
      "C": "Wall AC",
      "D": "Heat Pump",
      "E": "2 Units",
      "F": "3 or More",
      "G": "Common",
      "H": "Individual",
      "I": "Unit Control",
      "J": "Fan Coil",
      "K": "Other (See Remarks)",
      "L": "None",
      "M": "Active Solar",
      "N": "Geothermal Heat Pump",
      "O": "High Seer Heat Pump (12+)",
      "Q": "Passive Cooling",
      "R": "Swamp Cooler (Evaporative)",
      "S": "Wind",
      "V": "Ductless Mini-Split System"
    },
    "SF": {
      "A": "Central Air",
      "B": "Window AC",
      "C": "Wall AC",
      "D": "Heat Pump",
      "E": "2 Units",
      "F": "3 or More",
      "G": "Other (See Remarks)",
      "H": "None",
      "M": "Active Solar",
      "N": "Geothermal Heat Pump",
      "O": "High Seer Heat Pump (12+)",
      "P": "Overhangs Abv South Facing Windows",
      "Q": "Passive Cooling",
      "R": "Swamp Cooler (Evaporative)",
      "S": "Wind",
      "T": "ENERGY STAR",
      "U": "Air Source Heat Pumps (ASHP)",
      "V": "Ductless Mini-Split System"
    }
  },
  "ELECTRIC_FEATURE": {
    "CC": {
      "A": "110 Volts",
      "B": "220 Volts",
      "C": "Fuses",
      "D": "Circuit Breakers",
      "E": "60 Amps/Less",
      "F": "100 Amps",
      "G": "150 Amps",
      "H": "200 Amps",
      "I": "Other (See Remarks)",
      "M": "Knob & Tube Wiring",
      "N": "Net Meter",
      "O": "Time of Use Meter",
      "P": "Smart Grid Meter",
      "U": "Pre-Wired for Renewables",
      "V": "Ready for Renewables",
      "W": "400 Amps",
      "X": "EV Charging Station"
    },
    "MF": {
      "A": "110 Volts",
      "B": "220 Volts",
      "C": "Fuses",
      "D": "Circuit Breakers",
      "E": "60 Amps/Less",
      "F": "100 Amps",
      "G": "150 Amps",
      "H": "200 Amps",
      "I": "Common",
      "J": "Individually Metered",
      "K": "Varies per Unit",
      "L": "Other (See Remarks)",
      "M": "Knob & Tube Wiring",
      "U": "Pre-Wired for Renewables",
      "V": "Ready for Renewables",
      "W": "400 Amps",
      "X": "EV Charging Station"
    },
    "SF": {
      "A": "110 Volts",
      "B": "220 Volts",
      "C": "Fuses",
      "D": "Circuit Breakers",
      "E": "60 Amps/Less",
      "F": "100 Amps",
      "G": "150 Amps",
      "H": "200 Amps",
      "I": "Other (See Remarks)",
      "M": "Knob & Tube Wiring",
      "N": "Net Meter",
      "O": "Time of Use Meter",
      "P": "Smart Grid Meter",
      "U": "Pre-Wired for Renewables",
      "V": "Ready for Renewables",
      "W": "400 Amps",
      "X": "EV Charging Station"
    }
  },
  "ENERGY_FEATURES": {
    "CC": {
      "A": "Insulated Windows",
      "B": "Storm Windows",
      "C": "Insulated Doors",
      "D": "Storm Doors",
      "E": "Attic Vent Elec.",
      "F": "Solar Features",
      "G": "Partial",
      "H": "Prog. Thermostat",
      "I": "Other (See Remarks)",
      "K": "Backup Generator",
      "L": "WaterSense Fixtures",
      "M": "Solar Tubes"
    },
    "MF": {
      "A": "Insulated Windows",
      "B": "Storm Windows",
      "C": "Insulated Doors",
      "D": "Storm Doors",
      "E": "Attic Vent Elec.",
      "F": "Solar Features",
      "G": "Partial",
      "H": "Prog. Thermostat",
      "I": "Varies per Unit",
      "J": "Other (See Remarks)"
    },
    "SF": {
      "A": "Insulated Windows",
      "B": "Storm Windows",
      "C": "Insulated Doors",
      "D": "Storm Doors",
      "E": "Attic Vent Elec.",
      "F": "Solar Features",
      "G": "Partial",
      "H": "Prog. Thermostat",
      "I": "Other (See Remarks)",
      "K": "Backup Generator",
      "L": "WaterSense Fixtures",
      "M": "Solar Tubes"
    }
  },
  "EXTERIOR": {
    "CC": {
      "A": "Clapboard",
      "B": "Shingles",
      "C": "Wood",
      "D": "Aluminum",
      "E": "Vinyl",
      "F": "Asbestos",
      "G": "Masonite",
      "H": "Log",
      "I": "Brick",
      "J": "Stone",
      "K": "Shake",
      "L": "Stucco",
      "M": "Other (See Remarks)",
      "O": "Redwood",
      "P": "EIFS",
      "Q": "Fiber Cement Siding",
      "R": "Composite"
    },
    "MF": {
      "A": "Clapboard",
      "B": "Shingles",
      "C": "Wood",
      "D": "Aluminum",
      "E": "Vinyl",
      "F": "Asbestos",
      "G": "Masonite",
      "H": "Log",
      "I": "Brick",
      "J": "Stone",
      "K": "Shake",
      "L": "Stucco",
      "M": "Varies per Unit",
      "N": "Other (See Remarks)",
      "O": "Redwood",
      "P": "EIFS",
      "Q": "Fiber Cement Siding",
      "R": "Composite"
    },
    "SF": {
      "A": "Clapboard",
      "B": "Shingles",
      "C": "Wood",
      "D": "Aluminum",
      "E": "Vinyl",
      "F": "Asbestos",
      "G": "Masonite",
      "H": "Log",
      "I": "Brick",
      "J": "Stone",
      "K": "Shake",
      "L": "Stucco",
      "M": "Other (See Remarks)",
      "O": "Redwood",
      "P": "EIFS",
      "Q": "Fiber Cement Siding",
      "R": "Composite"
    }
  },
  "EXTERIOR_FEATURES": {
    "MF": {
      "1": "Gazebo",
      "2": "Deck - Roof",
      "3": "City View(s)",
      "4": "Integrated Pest Management",
      "6": "Drought Tolerant/Water Conserving Landscaping",
      "7": "Deck - Wood",
      "8": "Deck - Vinyl",
      "9": "Deck - Composite",
      "10": "Pool - Above Ground Heated",
      "11": "Pool - Inground Heated",
      "12": "Porch - Screened",
      "13": "Fruit Trees",
      "14": "Garden Area",
      "17": "Invisible Fence",
      "18": "Kennel",
      "19": "Outdoor Shower",
      "20": "Solar Powered Area Lighting",
      "21": "Stone Wall",
      "23": "Cistern Water Storage",
      "24": "ET Irrigation Controller",
      "A": "Porch",
      "B": "Porch - Enclosed",
      "C": "Deck",
      "D": "Patio",
      "E": "Patio - Enclosed",
      "F": "Covered Patio/Deck",
      "G": "Balcony",
      "H": "Pool - Inground",
      "I": "Pool - Above Ground",
      "J": "Cabana",
      "K": "Tennis Court",
      "L": "Handicap Access",
      "M": "Gutters",
      "N": "Hot Tub/Spa",
      "O": "Storage Shed",
      "P": "Barn/Stable",
      "Q": "Paddock",
      "R": "Greenhouse",
      "S": "Professional Landscaping",
      "T": "Sprinkler System",
      "U": "Decorative Lighting",
      "V": "Screens",
      "W": "Fenced Yard",
      "X": "Satellite Dish",
      "Y": "Varies per Unit",
      "Z": "Other (See Remarks)"
    },
    "RN": {
      "1": "Gazebo",
      "2": "Deck - Roof",
      "3": "City View(s)",
      "4": "Integrated Pest Management",
      "5": "Deck - Roof + Access Rights",
      "6": "Drought Tolerant/Water Conserving Landscaping",
      "7": "Deck - Wood",
      "8": "Deck - Vinyl",
      "9": "Deck - Composite",
      "10": "Pool - Above Ground Heated",
      "11": "Pool - Inground Heated",
      "12": "Porch - Screened",
      "13": "Fruit Trees",
      "14": "Garden Area",
      "17": "Invisible Fence",
      "18": "Kennel",
      "19": "Outdoor Shower",
      "20": "Solar Powered Area Lighting",
      "21": "Stone Wall",
      "22": "Deck - Access Rights",
      "23": "Cistern Water Storage",
      "24": "ET Irrigation Controller",
      "A": "Porch",
      "B": "Porch - Enclosed",
      "C": "Deck",
      "D": "Patio",
      "E": "Patio - Enclosed",
      "F": "Covered Patio/Deck",
      "G": "Balcony",
      "H": "Pool - Inground",
      "I": "Pool - Above Ground",
      "J": "Cabana",
      "K": "Tennis Court",
      "M": "Gutters",
      "N": "Hot Tub/Spa",
      "O": "Storage Shed",
      "P": "Barn/Stable",
      "Q": "Paddock",
      "R": "Greenhouse",
      "S": "Professional Landscaping",
      "T": "Sprinkler System",
      "U": "Decorative Lighting",
      "V": "Screens",
      "W": "Fenced Yard",
      "X": "Satellite Dish",
      "Y": "Other (See Remarks)"
    },
    "SF": {
      "1": "Gazebo",
      "2": "Deck - Roof",
      "3": "City View(s)",
      "4": "Integrated Pest Management",
      "6": "Drought Tolerant/Water Conserving Landscaping",
      "7": "Deck - Wood",
      "8": "Deck - Vinyl",
      "9": "Deck - Composite",
      "10": "Pool - Above Ground Heated",
      "11": "Pool - Inground Heated",
      "12": "Porch - Screened",
      "13": "Fruit Trees",
      "14": "Garden Area",
      "15": "Guest House",
      "16": "Horses Permitted",
      "17": "Invisible Fence",
      "18": "Kennel",
      "19": "Outdoor Shower",
      "20": "Solar Powered Area Lighting",
      "21": "Stone Wall",
      "23": "Cistern Water Storage",
      "24": "ET Irrigation Controller",
      "A": "Porch",
      "B": "Porch - Enclosed",
      "C": "Deck",
      "D": "Patio",
      "E": "Patio - Enclosed",
      "F": "Covered Patio/Deck",
      "G": "Balcony",
      "H": "Pool - Inground",
      "I": "Pool - Above Ground",
      "J": "Cabana",
      "K": "Tennis Court",
      "M": "Gutters",
      "N": "Hot Tub/Spa",
      "O": "Storage Shed",
      "P": "Barn/Stable",
      "Q": "Paddock",
      "R": "Greenhouse",
      "S": "Professional Landscaping",
      "T": "Sprinkler System",
      "U": "Decorative Lighting",
      "V": "Screens",
      "W": "Fenced Yard",
      "X": "Satellite Dish",
      "Y": "Other (See Remarks)"
    }
  },
  "FLOORING": {
    "CC": {
      "A": "Wood",
      "B": "Plywood",
      "C": "Tile",
      "D": "Vinyl",
      "E": "Wall to Wall Carpet",
      "F": "Concrete",
      "G": "Other (See Remarks)",
      "I": "Laminate",
      "J": "Marble",
      "K": "Bamboo",
      "L": "Eucalyptus",
      "M": "Hardwood",
      "N": "Particle Board",
      "O": "Pine",
      "P": "Recycled Wood",
      "Q": "Stone / Slate",
      "R": "Vinyl / VCT",
      "S": "Wood Laminate",
      "T": "Parquet",
      "U": "Engineered Hardwood",
      "V": "Renewable/Sustainable Flooring Materials",
      "W": "Green Labeled Carpets",
      "X": "Brick",
      "Y": "Luxury Vinyl Plank / LVP",
      "Z": "Luxury Vinyl Tile / LVT"
    },
    "MF": {
      "A": "Wood",
      "B": "Plywood",
      "C": "Tile",
      "D": "Vinyl",
      "E": "Wall to Wall Carpet",
      "F": "Concrete",
      "G": "Varies Per Unit",
      "H": "Other (See Remarks)",
      "I": "Laminate",
      "J": "Marble",
      "K": "Bamboo",
      "L": "Eucalyptus",
      "M": "Hardwood",
      "N": "Particle Board",
      "O": "Pine",
      "P": "Recycled Wood",
      "Q": "Stone / Slate",
      "R": "Vinyl / VCT",
      "S": "Wood Laminate",
      "T": "Parquet",
      "X": "Brick",
      "Y": "Luxury Vinyl Plank / LVP",
      "Z": "Luxury Vinyl Tile / LVT"
    },
    "RN": {
      "U": "Engineered Hardwood"
    },
    "SF": {
      "A": "Wood",
      "B": "Plywood",
      "C": "Tile",
      "D": "Vinyl",
      "E": "Wall to Wall Carpet",
      "F": "Concrete",
      "G": "Other (See Remarks)",
      "I": "Laminate",
      "J": "Marble",
      "K": "Bamboo",
      "L": "Eucalyptus",
      "M": "Hardwood",
      "N": "Particle Board",
      "O": "Pine",
      "P": "Recycled Wood",
      "Q": "Stone / Slate",
      "R": "Vinyl / VCT",
      "S": "Wood Laminate",
      "T": "Parquet",
      "U": "Engineered Hardwood",
      "V": "Renewable/Sustainable Flooring Materials",
      "W": "Green Labeled Carpets",
      "X": "Brick",
      "Y": "Luxury Vinyl Plank / LVP",
      "Z": "Luxury Vinyl Tile / LVT"
    }
  },
  "GARAGE_PARKING": {
    "CC": {
      "A": "Attached",
      "B": "Detached",
      "C": "Under",
      "D": "Carport",
      "E": "Garage Door Opener",
      "F": "Heated",
      "G": "Storage",
      "H": "Work Area",
      "I": "Deeded",
      "J": "Assigned",
      "K": "Common",
      "L": "Side Entry",
      "M": "Insulated",
      "N": "Carriage Shed",
      "O": "Barn"
    },
    "RN": {
      "A": "Attached",
      "B": "Detached",
      "C": "Under",
      "D": "Carport",
      "E": "Garage Door Opener",
      "F": "Heated",
      "G": "Storage",
      "H": "Work Area",
      "I": "Deeded",
      "J": "Assigned",
      "K": "Common",
      "L": "Side Entry",
      "M": "Insulated",
      "N": "Carriage Shed",
      "O": "Barn"
    },
    "SF": {
      "A": "Attached",
      "B": "Detached",
      "C": "Under",
      "D": "Carport",
      "E": "Garage Door Opener",
      "F": "Heated",
      "G": "Storage",
      "H": "Work Area",
      "L": "Side Entry",
      "M": "Insulated",
      "N": "Carriage Shed",
      "O": "Barn",
      "P": "Oversized Parking"
    }
  },
  "HANDICAP_AMENITIES": {
    "CC": {
      "A": "Adj. Height Sink-No Cabinets Blw",
      "B": "Chair Lift",
      "C": "Handicap Fixtures",
      "D": "Elevator",
      "E": "Extra Wide Shower",
      "F": "Extra Wide Doors",
      "G": "Extra Wide Halls",
      "H": "Flat Thresholds",
      "I": "Handicap Access ONLY",
      "J": "Handicap Door Handles",
      "K": "Handicap Equipped",
      "L": "Low Pile Carpet",
      "M": "Lowered Light Switches",
      "N": "Pool Lift",
      "O": "Raised Toilet",
      "P": "Ramp(s)/No Steps",
      "Q": "Ramp(s)/Level Entrance",
      "R": "Ramp(s)/Level From Garage",
      "S": "Reserved Parking",
      "T": "Rocker Light Switch",
      "U": "Roll Under Counter(s)",
      "V": "Roll-in Shower",
      "W": "Single Level",
      "X": "Tub/Shower Grab Assist Bars",
      "Y": "Walk-in Tub"
    },
    "RN": {
      "A": "Adj. Height Sink-No Cabinets Blw",
      "B": "Chair Lift",
      "C": "Handicap Fixtures",
      "D": "Elevator",
      "E": "Extra Wide Shower",
      "F": "Extra Wide Doors",
      "G": "Extra Wide Halls",
      "H": "Flat Thresholds",
      "I": "Handicap Access ONLY",
      "J": "Handicap Door Handles",
      "K": "Handicap Equipped",
      "L": "Low Pile Carpet",
      "M": "Lowered Light Switches",
      "N": "Pool Lift",
      "O": "Raised Toilet",
      "P": "Ramp(s)/No Steps",
      "Q": "Ramp(s)/Level Entrance",
      "R": "Ramp(s)/Level From Garage",
      "S": "Reserved Parking",
      "T": "Rocker Light Switch",
      "U": "Roll Under Counter(s)",
      "V": "Roll-in Shower",
      "W": "Single Level",
      "X": "Tub/Shower Grab Assist Bars",
      "Y": "Walk-in Tub"
    },
    "SF": {
      "A": "Adj. Height Sink-No Cabinets Blw",
      "B": "Chair Lift",
      "C": "Handicap Fixtures",
      "D": "Elevator",
      "E": "Extra Wide Shower",
      "F": "Extra Wide Doors",
      "G": "Extra Wide Halls",
      "H": "Flat Thresholds",
      "I": "Handicap Access ONLY",
      "J": "Handicap Door Handles",
      "K": "Handicap Equipped",
      "L": "Low Pile Carpet",
      "M": "Lowered Light Switches",
      "N": "Pool Lift",
      "O": "Raised Toilet",
      "P": "Ramp(s)/No Steps",
      "Q": "Ramp(s)/Level Entrance",
      "R": "Ramp(s)/Level From Garage",
      "S": "Reserved Parking",
      "T": "Rocker Light Switch",
      "U": "Roll Under Counter(s)",
      "V": "Roll-in Shower",
      "W": "Single Level",
      "X": "Tub/Shower Grab Assist Bars",
      "Y": "Walk-in Tub"
    }
  },
  "HEATING": {
    "CC": {
      "1": "Wind",
      "2": "Floor Furnace",
      "3": "Hot Air Gravity",
      "4": "Humidifier",
      "5": "Propane",
      "6": "Space Heater",
      "7": "Radiant",
      "8": "ENERGY STAR",
      "9": "Air Source Heat Pumps (ASHP)",
      "10": "Solar Thermal Collection",
      "11": "Pellet Stove",
      "12": "Wood Stove",
      "13": "Ductless Mini-Split System",
      "14": "Leased Propane Tank",
      "A": "Central Heat",
      "B": "Forced Air",
      "C": "Hot Water Baseboard",
      "D": "Electric Baseboard",
      "E": "Hot Water Radiators",
      "F": "Steam",
      "G": "Heat Pump",
      "H": "Oil",
      "I": "Gas",
      "J": "Electric",
      "K": "Wood",
      "L": "Common",
      "M": "Individual",
      "N": "Unit Control",
      "O": "Wall Unit",
      "P": "Fan Coil",
      "Q": "Extra Flue",
      "R": "Other (See Remarks)",
      "S": "None",
      "U": "Hydro Air",
      "V": "Geothermal Heat Source",
      "W": "Active Solar",
      "X": "Ground Source Heat Pump",
      "Y": "Hydronic Floor Heat(Radiant)",
      "Z": "Passive Solar"
    },
    "MF": {
      "1": "Wind",
      "2": "Floor Furnace",
      "3": "Hot Air Gravity",
      "4": "Humidifier",
      "5": "Propane",
      "6": "Space Heater",
      "7": "Radiant",
      "11": "Pellet Stove",
      "12": "Wood Stove",
      "13": "Ductless Mini-Split System",
      "14": "Leased Propane Tank",
      "A": "Central Heat",
      "B": "Forced Air",
      "C": "Hot Water Baseboard",
      "D": "Electric Baseboard",
      "E": "Hot Water Radiators",
      "F": "Steam",
      "G": "Heat Pump",
      "H": "Oil",
      "I": "Gas",
      "J": "Electric",
      "K": "Wood",
      "L": "Common",
      "M": "Individual",
      "N": "Unit Control",
      "O": "Wall Unit",
      "P": "Fan Coil",
      "Q": "Extra Flue",
      "R": "Other (See Remarks)",
      "S": "None",
      "T": "Geothermal Heat Pump",
      "U": "Hydro Air",
      "W": "Active Solar",
      "X": "Ground Source Heat Pump",
      "Y": "Hydronic Floor Heat(Radiant)",
      "Z": "Passive Solar"
    },
    "RN": {
      "1": "Wall Unit",
      "2": "Space Heater",
      "3": "Radiant",
      "4": "Wind",
      "5": "Fan Coil",
      "11": "Pellet Stove",
      "12": "Wood Stove",
      "13": "Ductless Mini-Split System",
      "14": "Leased Propane Tank",
      "A": "Electric",
      "B": "Oil",
      "C": "Gas",
      "D": "Other (See Remarks)",
      "E": "Active Solar",
      "F": "Central Heat",
      "G": "Common",
      "H": "Electric Baseboard",
      "I": "Extra Flue",
      "J": "Forced Air",
      "K": "Floor Furnace",
      "L": "Ground Source Heat Pump",
      "M": "Geothermal Heat Source",
      "N": "Hot Air Gravity",
      "O": "Hot Water Baseboard",
      "P": "Hot Water Radiators",
      "Q": "Hydro Air",
      "R": "Heat Pump",
      "S": "Humidifier",
      "T": "Hydronic Floor Heat(Radiant)",
      "U": "Individual",
      "V": "None",
      "W": "Passive Solar",
      "X": "Propane",
      "Y": "Steam",
      "Z": "Unit Control"
    },
    "SF": {
      "1": "Wind",
      "8": "ENERGY STAR",
      "9": "Air Source Heat Pumps (ASHP)",
      "10": "Solar Thermal Collection",
      "11": "Pellet Stove",
      "12": "Wood Stove",
      "13": "Ductless Mini-Split System",
      "14": "Leased Propane Tank",
      "A": "Central Heat",
      "B": "Forced Air",
      "C": "Hot Air Gravity",
      "D": "Hot Water Baseboard",
      "E": "Electric Baseboard",
      "F": "Hot Water Radiators",
      "G": "Steam",
      "H": "Radiant",
      "I": "Heat Pump",
      "J": "Space Heater",
      "K": "Floor Furnace",
      "L": "Humidifier",
      "M": "Oil",
      "N": "Gas",
      "O": "Electric",
      "P": "Propane",
      "Q": "Wood",
      "R": "Extra Flue",
      "S": "Other (See Remarks)",
      "T": "None",
      "U": "Hydro Air",
      "V": "Geothermal Heat Source",
      "W": "Active Solar",
      "X": "Ground Source Heat Pump",
      "Y": "Hydronic Floor Heat(Radiant)",
      "Z": "Passive Solar"
    }
  },
  "HOT_WATER": {
    "CC": {
      "A": "Oil",
      "B": "Natural Gas",
      "C": "Electric",
      "D": "Propane Gas",
      "E": "Solar",
      "F": "Tank",
      "G": "Tankless",
      "H": "Separate Booster",
      "I": "Leased Heater",
      "J": "Other (See Remarks)",
      "K": "Geothermal/GSHP Hot Water"
    },
    "MF": {
      "A": "Oil",
      "B": "Natural Gas",
      "C": "Electric",
      "D": "Propane Gas",
      "E": "Solar",
      "F": "Tank",
      "G": "Tankless",
      "H": "Separate Booster",
      "I": "Leased Heater",
      "J": "Varies Per Unit",
      "K": "Other (See Remarks)",
      "L": "Solar Water Heating"
    },
    "SF": {
      "A": "Oil",
      "B": "Natural Gas",
      "C": "Electric",
      "D": "Propane Gas",
      "E": "Solar",
      "F": "Tank",
      "G": "Tankless",
      "H": "Separate Booster",
      "I": "Leased Heater",
      "J": "Other (See Remarks)",
      "K": "Geothermal/GSHP Hot Water"
    }
  },
  "INSULATION_FEATURE": {
    "CC": {
      "1": "Spray Foam",
      "2": "Soy-Based Spray Foam",
      "3": "UFFI Foam",
      "A": "Full",
      "B": "Partial",
      "C": "Fiberglass",
      "D": "Loose",
      "E": "Blown In",
      "F": "Styrofoam",
      "G": "Mixed",
      "H": "Other (See Remarks)",
      "I": "Unknown",
      "J": "None",
      "K": "Asbestos",
      "L": "Cellulose - Fiber",
      "M": "Cellulose - Sprayed",
      "N": "Fiberglass - Batts",
      "O": "Fiberglass - Loose",
      "P": "Fiberglass - Rigid",
      "Q": "Foam",
      "R": "Mica Chips",
      "S": "Mineral Board",
      "T": "Mineral Fiber",
      "U": "Mineral Wool",
      "V": "Polystyrene EPS",
      "W": "Polyisocyanurate Board",
      "X": "Polyicynene Foam",
      "Y": "Polyurethane Foam",
      "Z": "Polystyrene-XPS"
    },
    "SF": {
      "1": "Spray Foam",
      "2": "Soy-Based Spray Foam",
      "3": "UFFI Foam",
      "A": "Full",
      "B": "Partial",
      "C": "Fiberglass",
      "D": "Loose",
      "E": "Blown In",
      "F": "Styrofoam",
      "G": "Mixed",
      "H": "Other (See Remarks)",
      "I": "Unknown",
      "J": "None",
      "K": "Asbestos",
      "L": "Cellulose - Fiber",
      "M": "Cellulose - Sprayed",
      "N": "Fiberglass - Batts",
      "O": "Fiberglass - Loose",
      "P": "Fiberglass - Rigid",
      "Q": "Foam",
      "R": "Mica Chips",
      "S": "Mineral Board",
      "T": "Mineral Fiber",
      "U": "Mineral Wool",
      "V": "Polystyrene EPS",
      "W": "Polyisocyanurate Board",
      "X": "Polyicynene Foam",
      "Y": "Polyurethane Foam",
      "Z": "Polystyrene-XPS"
    }
  },
  "INTERIOR_FEATURES": {
    "CC": {
      "A": "Central Vacuum",
      "C": "Security System",
      "D": "Cable Available",
      "E": "Sauna/Steam/Hot Tub",
      "F": "Wetbar",
      "G": "Intercom",
      "H": "Walk-up Attic",
      "I": "Other (See Remarks)",
      "J": "Whole House Fan",
      "K": "Finish - Cement Plaster",
      "L": "Finish - Earthen Plaster",
      "M": "Finish - Sheetrock",
      "N": "French Doors",
      "O": "Indoor Pool",
      "P": "Laundry Chute",
      "Q": "Wired for Surround Sound",
      "R": "Internet Available - Broadband",
      "S": "Internet Available - DSL",
      "T": "Internet Available - Fiber-Optic",
      "U": "Internet Available - Satellite",
      "V": "Internet Available - Unknown",
      "W": "Elevator"
    },
    "SF": {
      "A": "Central Vacuum",
      "C": "Security System",
      "D": "Cable Available",
      "E": "Sauna/Steam/Hot Tub",
      "F": "Wetbar",
      "G": "Intercom",
      "H": "Walk-up Attic",
      "I": "Other (See Remarks)",
      "J": "Whole House Fan",
      "K": "Finish - Cement Plaster",
      "L": "Finish - Earthen Plaster",
      "M": "Finish - Sheetrock",
      "N": "French Doors",
      "O": "Indoor Pool",
      "P": "Laundry Chute",
      "Q": "Wired for Surround Sound",
      "R": "Internet Available - Broadband",
      "S": "Internet Available - DSL",
      "T": "Internet Available - Fiber-Optic",
      "U": "Internet Available - Satellite",
      "V": "Internet Available - Unknown",
      "W": "Elevator"
    }
  },
  "LAUNDRY_FEATURES": {
    "CC": {
      "A": "Common",
      "B": "In Building",
      "C": "In Unit",
      "D": "Off-Site"
    },
    "RN": {
      "A": "Common",
      "B": "In Building",
      "C": "In Unit",
      "D": "Off-Site",
      "E": "Dryer Hookups in Unit",
      "F": "Washer Hookups in Unit"
    }
  },
  "LOT_DESCRIPTION": {
    "MF": {
      "A": "Corner",
      "B": "Wooded",
      "C": "Paved Drive",
      "D": "Easements",
      "E": "Underground Storage Tank",
      "F": "Stream",
      "G": "Golf Course Frontage",
      "H": "Additional Land Avail.",
      "I": "Zero Lot Line",
      "J": "Flood Plain",
      "K": "Other (See Remarks)",
      "L": "Shared Drive",
      "M": "City View(s)",
      "N": "Cleared",
      "O": "Farmland",
      "P": "Fenced/Enclosed",
      "Q": "Fill Needed",
      "R": "Gentle Slope",
      "S": "Level",
      "T": "Marsh",
      "U": "Sloping",
      "V": "Steep Slope",
      "W": "Scenic View(s)"
    },
    "SF": {
      "A": "Corner",
      "B": "Wooded",
      "C": "Paved Drive",
      "D": "Easements",
      "E": "Underground Storage Tank",
      "F": "Stream",
      "G": "Golf Course Frontage",
      "H": "Additional Land Avail.",
      "I": "Zero Lot Line",
      "J": "Flood Plain",
      "K": "Other (See Remarks)",
      "L": "Shared Drive",
      "M": "City View(s)",
      "N": "Cleared",
      "O": "Farmland",
      "P": "Fenced/Enclosed",
      "Q": "Fill Needed",
      "R": "Gentle Slope",
      "S": "Level",
      "T": "Marsh",
      "U": "Sloping",
      "V": "Steep Slope",
      "W": "Scenic View(s)"
    }
  },
  "MF_TYPE": {
    "MF": {
      "A": "2 Family",
      "B": "3 Family",
      "C": "4 Family",
      "D": "Duplex",
      "E": "5-9 Family",
      "F": "2 Family - 2 Units Side by Side",
      "G": "2 Family - 2 Units Up/Down",
      "H": "2 Family - Rooming House",
      "I": "3 Family - 3 Units Side by Side",
      "J": "3 Family - 3 Units Up/Down",
      "K": "3 Family - Rooming House",
      "L": "4 Family - 4 Units Side by Side",
      "M": "4 Family - 4 Units Up/Down",
      "N": "4 Family - Rooming House",
      "O": "5+ Family - 5+ Units Side by Side",
      "P": "5+ Family - 5+ Units Up/Down",
      "Q": "5+ Family - Rooming House"
    }
  },
  "PARKING_FEATURE": {
    "CC": {
      "A": "Off-Street",
      "B": "Rented",
      "C": "Tandem",
      "D": "On Street Permit",
      "E": "Assigned",
      "F": "Deeded",
      "G": "Common",
      "H": "Guest",
      "J": "Available for Purchase",
      "L": "Improved Driveway",
      "M": "Stone/Gravel",
      "N": "Paved Driveway",
      "O": "Unpaved Driveway",
      "P": "Leased",
      "Q": "No parking",
      "R": "Exclusive Parking",
      "S": "Permeable Pavement",
      "V": "On Street Without Permit"
    },
    "MF": {
      "A": "Off-Street",
      "B": "Rented",
      "C": "Tandem",
      "D": "On Street Permit",
      "E": "Assigned",
      "F": "Other (See Remarks)",
      "G": "Common",
      "H": "Guest",
      "I": "Deeded",
      "J": "Available for Purchase",
      "L": "Improved Driveway",
      "M": "Stone/Gravel",
      "N": "Paved Driveway",
      "O": "Unpaved Driveway",
      "V": "On Street Without Permit"
    },
    "RN": {
      "A": "Off-Street",
      "B": "Rented",
      "D": "On Street Permit",
      "E": "Assigned",
      "F": "Deeded",
      "G": "Common",
      "H": "Guest",
      "J": "Available for Purchase",
      "L": "Improved Driveway",
      "M": "Stone/Gravel",
      "N": "Paved Driveway",
      "V": "On Street Without Permit"
    },
    "SF": {
      "A": "Off-Street",
      "B": "Rented",
      "C": "Tandem",
      "D": "On Street Permit",
      "E": "Assigned",
      "I": "Deeded",
      "J": "Available for Purchase",
      "L": "Improved Driveway",
      "M": "Stone/Gravel",
      "N": "Paved Driveway",
      "O": "Unpaved Driveway",
      "S": "Permeable Pavement",
      "V": "On Street Without Permit"
    }
  },
  "PETS_ALLOWED": {
    "CC": {
      "N": "No",
      "R": "Yes w/ Restrictions",
      "U": "Unknown",
      "Y": "Yes"
    },
    "RN": {
      "N": "No",
      "R": "Yes w/ Restrictions",
      "Y": "Yes"
    }
  },
  "POOL_DESCRIPTION": {
    "CC": {
      "A": "Above Ground",
      "B": "Inground",
      "C": "Indoor",
      "D": "Heated",
      "E": "Lap"
    },
    "RN": {
      "A": "Above Ground",
      "B": "Inground",
      "C": "Indoor",
      "D": "Heated",
      "E": "Lap"
    }
  },
  "RN_TYPE": {
    "RN": {
      "A": "Single Family",
      "B": "Attached (Townhouse/Rowhouse/Duplex)",
      "C": "Condominium",
      "D": "Apartment",
      "E": "Mobile Home",
      "F": "Farm",
      "G": "Parking"
    }
  },
  "ROAD_TYPE": {
    "MF": {
      "A": "Public",
      "B": "Private",
      "C": "Paved",
      "D": "Unpaved",
      "E": "Publicly Maint.",
      "F": "Privately Maint.",
      "G": "Cul-De-Sac",
      "H": "Dead End",
      "I": "Sidewalk",
      "J": "Paper Road"
    },
    "SF": {
      "A": "Public",
      "B": "Private",
      "C": "Paved",
      "D": "Unpaved",
      "E": "Publicly Maint.",
      "F": "Privately Maint.",
      "G": "Cul-De-Sac",
      "H": "Dead End",
      "I": "Sidewalk",
      "J": "Paper Road"
    }
  },
  "ROOF_MATERIAL": {
    "CC": {
      "A": "Asphalt/Fiberglass Shingles",
      "B": "Wood Shingles",
      "C": "Tile",
      "D": "Slate",
      "E": "Tar & Gravel",
      "F": "Shake",
      "G": "Rubber",
      "H": "Other (See Remarks)",
      "I": "Metal",
      "J": "Asphalt/Composition Shingles",
      "K": "Clay",
      "L": "Living",
      "M": "Metal Roofing (Recycled)",
      "N": "Radiant Roof Barriers",
      "O": "Terne - Coated - Stainless",
      "P": "Vegetation/Garden",
      "V": "Reflective Roofing-ENERGY STAR",
      "W": "Solar Shingles"
    },
    "MF": {
      "A": "Asphalt/Fiberglass Shingles",
      "B": "Wood Shingles",
      "C": "Tile",
      "D": "Slate",
      "E": "Tar & Gravel",
      "F": "Shake",
      "G": "Rubber",
      "H": "Other (See Remarks)",
      "I": "Metal",
      "J": "Asphalt/Composition Shingles",
      "K": "Clay",
      "L": "Living",
      "M": "Metal Roofing (Recycled)",
      "N": "Radiant Roof Barriers",
      "O": "Terne - Coated - Stainless",
      "P": "Vegetation/Garden",
      "V": "Reflective Roofing-ENERGY STAR"
    },
    "SF": {
      "A": "Asphalt/Fiberglass Shingles",
      "B": "Wood Shingles",
      "C": "Tile",
      "D": "Slate",
      "E": "Tar & Gravel",
      "F": "Shake",
      "G": "Rubber",
      "H": "Other (See Remarks)",
      "I": "Metal",
      "J": "Asphalt/Composition Shingles",
      "K": "Clay",
      "L": "Living",
      "M": "Metal Roofing (Recycled)",
      "N": "Radiant Roof Barriers",
      "O": "Terne - Coated - Stainless",
      "P": "Vegetation/Garden",
      "V": "Reflective Roofing-ENERGY STAR",
      "W": "Solar Shingles"
    }
  },
  "SEWER": {
    "CC": {
      "A": "City/Town Sewer",
      "B": "Inspection Required for Sale",
      "C": "Private Sewerage",
      "D": "Pumice Wick",
      "E": "Rock/Reed",
      "F": "Other (See Remarks)",
      "G": "Tight Tank"
    },
    "MF": {
      "A": "City/Town Sewer",
      "B": "Inspection Required for Sale",
      "C": "Private Sewerage",
      "F": "Other (See Remarks)",
      "G": "Tight Tank"
    },
    "SF": {
      "A": "City/Town Sewer",
      "B": "Inspection Required for Sale",
      "C": "Private Sewerage",
      "D": "Pumice Wick",
      "E": "Rock/Reed",
      "F": "Other (See Remarks)",
      "G": "Tight Tank"
    }
  },
  "SEWER_AND_WATER": {
    "CC": {
      "A": "City/Town Water",
      "B": "Private Water",
      "C": "Shared Well",
      "D": "Community Well",
      "E": "City/Town Sewer",
      "F": "Private Sewerage",
      "G": "Inspection Required for Sale",
      "H": "Individual Meter",
      "I": "Other (See Remarks)",
      "J": "Pumice Wick",
      "K": "Individual Well",
      "L": "Rain Water",
      "M": "Rock/Reed"
    },
    "MF": {
      "A": "City/Town Water",
      "B": "Private Water",
      "C": "Shared Well",
      "D": "Community Well",
      "E": "City/Town Sewer",
      "F": "Private Sewerage",
      "G": "Inspection Required for Sale",
      "H": "Individual Meter",
      "I": "Other (See Remarks)"
    },
    "SF": {
      "A": "City/Town Water",
      "B": "Private Water",
      "C": "Shared Well",
      "D": "Community Well",
      "E": "City/Town Sewer",
      "F": "Private Sewerage",
      "G": "Inspection Required for Sale",
      "H": "Other (See Remarks)",
      "J": "Pumice Wick",
      "L": "Rain Water",
      "M": "Rock/Reed"
    }
  },
  "SF_TYPE": {
    "SF": {
      "A": "Detached",
      "B": "Attached",
      "D": "Farm",
      "E": "Equestrian"
    }
  },
  "STATUS": {
    "CC": {
      "ACT": "Active",
      "BOM": "Back on Market",
      "CAN": "Canceled",
      "CSO": "Coming Soon",
      "CTG": "Contingent",
      "EXP": "Expired",
      "EXT": "Extended",
      "KIL": "Killed",
      "NEW": "New",
      "PCG": "Price Changed",
      "RAC": "Reactivated",
      "RNT": "Rented",
      "SLD": "Sold",
      "UAG": "Under Agreement",
      "WDN": "Temporarily Withdrawn"
    },
    "MF": {
      "ACT": "Active",
      "BOM": "Back on Market",
      "CAN": "Canceled",
      "CSO": "Coming Soon",
      "CTG": "Contingent",
      "EXP": "Expired",
      "EXT": "Extended",
      "KIL": "Killed",
      "NEW": "New",
      "PCG": "Price Changed",
      "RAC": "Reactivated",
      "RNT": "Rented",
      "SLD": "Sold",
      "UAG": "Under Agreement",
      "WDN": "Temporarily Withdrawn"
    },
    "RN": {
      "ACT": "Active",
      "BOM": "Back on Market",
      "CAN": "Canceled",
      "CSO": "Coming Soon",
      "CTG": "Contingent",
      "EXP": "Expired",
      "EXT": "Extended",
      "KIL": "Killed",
      "NEW": "New",
      "PCG": "Price Changed",
      "RAC": "Reactivated",
      "RNT": "Rented",
      "SLD": "Sold",
      "UAG": "Under Agreement",
      "WDN": "Temporarily Withdrawn"
    },
    "SF": {
      "ACT": "Active",
      "BOM": "Back on Market",
      "CAN": "Canceled",
      "CSO": "Coming Soon",
      "CTG": "Contingent",
      "EXP": "Expired",
      "EXT": "Extended",
      "KIL": "Killed",
      "NEW": "New",
      "PCG": "Price Changed",
      "RAC": "Reactivated",
      "RNT": "Rented",
      "SLD": "Sold",
      "UAG": "Under Agreement",
      "WDN": "Temporarily Withdrawn"
    }
  },
  "STYLE": {
    "CC": {
      "A": "Detached",
      "B": "Townhouse",
      "C": "Rowhouse",
      "D": "Garden",
      "E": "Half-Duplex",
      "F": "High-Rise",
      "G": "Mid-Rise",
      "H": "Low-Rise",
      "I": "2/3 Family",
      "J": "Brownstone",
      "K": "Courtyard",
      "L": "Motel/Cottage/Efficiency",
      "M": "Other (See Remarks)",
      "N": "Loft",
      "O": "Attached",
      "P": "Philadelphia",
      "W": "Shingle",
      "X": "Duplex"
    },
    "SF": {
      "1": "Craftsman",
      "2": "Georgian",
      "3": "Queen Anne",
      "4": "Spanish Colonial",
      "5": "Italianate",
      "6": "Dutch Colonial",
      "7": "French Colonial",
      "8": "Gothic Revival",
      "9": "Second Empire",
      "10": "Colonial Revival",
      "11": "Neoclassical",
      "12": "Prairie",
      "13": "Octagon",
      "14": "Federal",
      "15": "Chateauesque",
      "A": "Colonial",
      "B": "Garrison",
      "C": "Cape",
      "D": "Contemporary",
      "E": "Ranch",
      "F": "Raised Ranch",
      "G": "Split Entry",
      "H": "Victorian",
      "I": "Tudor",
      "J": "Gambrel/Dutch",
      "K": "Antique",
      "L": "Farmhouse",
      "M": "Saltbox",
      "N": "Cottage",
      "O": "Bungalow",
      "P": "Other (See Remarks)",
      "Q": "Multi-Level",
      "S": "Log",
      "T": "Front to Back Split",
      "U": "Lofted Split",
      "V": "Greek Revival",
      "W": "Shingle",
      "X": "Mid-Century Modern",
      "Y": "Villa",
      "Z": "Carriage House"
    }
  },
  "UNIT_PLACEMENT": {
    "CC": {
      "A": "Below Grade",
      "B": "Street",
      "C": "Upper",
      "D": "Top/Penthouse",
      "E": "End",
      "F": "Middle",
      "G": "Corner",
      "H": "Front",
      "I": "Back",
      "J": "Ground",
      "K": "Lower Level",
      "L": "Partially Below Grade",
      "M": "Walkout",
      "N": "Courtyard",
      "O": "Garden"
    },
    "RN": {
      "A": "Below Grade",
      "B": "Street",
      "C": "Upper",
      "D": "Top/Penthouse",
      "E": "End",
      "F": "Middle",
      "G": "Corner",
      "H": "Front",
      "I": "Back",
      "J": "Ground",
      "K": "Lower Level",
      "L": "Partially Below Grade",
      "M": "Walkout",
      "N": "Courtyard",
      "O": "Garden"
    }
  },
  "WATER": {
    "CC": {
      "A": "City/Town Water",
      "B": "Community Well",
      "C": "Individual Meter",
      "D": "Individual Well",
      "E": "Private Water",
      "F": "Rain Water",
      "G": "Shared Well",
      "H": "Other (See Remarks)",
      "I": "Reclaimed Water System",
      "J": "Greywater Reuse System"
    },
    "MF": {
      "A": "City/Town Water",
      "B": "Community Well",
      "C": "Individual Meter",
      "E": "Private Water",
      "G": "Shared Well",
      "H": "Other (See Remarks)"
    },
    "SF": {
      "A": "City/Town Water",
      "B": "Community Well",
      "E": "Private Water",
      "F": "Rain Water",
      "G": "Shared Well",
      "H": "Other (See Remarks)",
      "I": "Reclaimed Water System",
      "J": "Greywater Reuse System"
    }
  },
  "WATERFRONT": {
    "CC": {
      "A": "Ocean",
      "B": "Sound",
      "C": "Lake",
      "D": "River",
      "E": "Pond",
      "F": "Bay",
      "G": "Harbor",
      "H": "Dock/Mooring",
      "I": "Frontage",
      "J": "Walk to",
      "L": "Access",
      "M": "Other (See Remarks)",
      "N": "Canal",
      "O": "Bog",
      "P": "Creek",
      "Q": "Deep Water Access",
      "R": "Direct Access",
      "S": "Marina",
      "T": "Marsh",
      "U": "Navigable",
      "V": "Public",
      "W": "Private"
    },
    "MF": {
      "A": "Ocean",
      "B": "Sound",
      "C": "Lake",
      "D": "River",
      "E": "Pond",
      "F": "Bay",
      "G": "Harbor",
      "H": "Dock/Mooring",
      "I": "Frontage",
      "J": "Walk to",
      "L": "Access",
      "M": "Other (See Remarks)",
      "N": "Canal",
      "O": "Bog",
      "P": "Creek",
      "Q": "Deep Water Access",
      "R": "Direct Access",
      "S": "Marina",
      "T": "Marsh",
      "U": "Navigable",
      "V": "Public",
      "W": "Private"
    },
    "RN": {
      "A": "Ocean",
      "B": "Sound",
      "C": "Lake",
      "D": "River",
      "E": "Pond",
      "F": "Bay",
      "G": "Harbor",
      "H": "Dock/Mooring",
      "I": "Frontage",
      "J": "Walk to",
      "L": "Access",
      "M": "Other (See Remarks)",
      "N": "Canal",
      "O": "Bog",
      "P": "Creek",
      "Q": "Deep Water Access",
      "R": "Direct Access",
      "S": "Marina",
      "T": "Marsh",
      "U": "Navigable",
      "V": "Public",
      "W": "Private"
    },
    "SF": {
      "A": "Ocean",
      "B": "Sound",
      "C": "Lake",
      "D": "River",
      "E": "Pond",
      "F": "Bay",
      "G": "Harbor",
      "H": "Dock/Mooring",
      "I": "Frontage",
      "J": "Walk to",
      "L": "Access",
      "M": "Other (See Remarks)",
      "N": "Canal",
      "O": "Bog",
      "P": "Creek",
      "Q": "Deep Water Access",
      "R": "Direct Access",
      "S": "Marina",
      "T": "Marsh",
      "U": "Navigable",
      "V": "Public",
      "W": "Private"
    }
  },
  "WATERVIEW_FEATURES": {
    "CC": {
      "A": "Bay",
      "B": "Bog",
      "C": "Canal",
      "D": "Creek",
      "E": "Dock/Mooring",
      "F": "Harbor",
      "G": "Lake",
      "H": "Marina",
      "I": "Marsh",
      "J": "Ocean",
      "K": "Pond",
      "L": "Private",
      "M": "Public",
      "N": "River",
      "O": "Sound",
      "P": "Walk to",
      "Q": "Other (See Remarks)"
    },
    "MF": {
      "A": "Bay",
      "B": "Bog",
      "C": "Canal",
      "D": "Creek",
      "E": "Dock/Mooring",
      "F": "Harbor",
      "G": "Lake",
      "H": "Marina",
      "I": "Marsh",
      "J": "Ocean",
      "K": "Pond",
      "L": "Private",
      "M": "Public",
      "N": "River",
      "O": "Sound",
      "P": "Walk to",
      "Q": "Other (See Remarks)"
    },
    "RN": {
      "A": "Bay",
      "B": "Bog",
      "C": "Canal",
      "D": "Creek",
      "E": "Dock/Mooring",
      "F": "Harbor",
      "G": "Lake",
      "H": "Marina",
      "I": "Marsh",
      "J": "Ocean",
      "K": "Pond",
      "L": "Private",
      "M": "Public",
      "N": "River",
      "O": "Sound",
      "P": "Walk to",
      "Q": "Other (See Remarks)"
    },
    "SF": {
      "A": "Bay",
      "B": "Bog",
      "C": "Canal",
      "D": "Creek",
      "E": "Dock/Mooring",
      "F": "Harbor",
      "G": "Lake",
      "H": "Marina",
      "I": "Marsh",
      "J": "Ocean",
      "K": "Pond",
      "L": "Private",
      "M": "Public",
      "N": "River",
      "O": "Sound",
      "P": "Walk to",
      "Q": "Other (See Remarks)"
    }
  },
  "YEAR_BUILT_DESCRP": {
    "CC": {
      "A": "Actual",
      "B": "Approximate",
      "C": "Certified Historic",
      "D": "Renovated Since",
      "E": "To Be Built",
      "F": "Under Construction",
      "G": "Unknown/Mixed",
      "H": "Finished, Never Occupied"
    },
    "MF": {
      "A": "Actual",
      "B": "Approximate",
      "C": "Certified Historic",
      "D": "Renovated Since",
      "E": "To Be Built",
      "F": "Under Construction",
      "G": "Unknown/Mixed",
      "H": "Finished, Never Occupied"
    },
    "RN": {
      "A": "Actual",
      "B": "Approximate",
      "C": "Certified Historic",
      "D": "Renovated Since",
      "E": "To Be Built",
      "F": "Under Construction",
      "G": "Unknown/Mixed",
      "H": "Finished, Never Occupied"
    },
    "SF": {
      "A": "Actual",
      "B": "Approximate",
      "C": "Certified Historic",
      "D": "Renovated Since",
      "E": "To Be Built",
      "F": "Under Construction",
      "G": "Unknown/Mixed",
      "H": "Finished, Never Occupied"
    }
  }
};
