// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

/**
 * This module is imported by AuthContext, which lives in the root layout — so
 * it is in EVERY route's module graph, including during static generation.
 *
 * It therefore must import cleanly with no `window`. It previously threw here
 * when `window` was undefined, which hard-crashed the prerender on the first
 * page. The client-only behaviour is now scoped to the auth options below
 * (session persistence and URL-hash detection both need browser storage), and
 * nothing at module scope touches `window` directly.
 */
const IS_BROWSER = typeof window !== 'undefined';

// Use Vite's import.meta.env for environment variables
// Also check process.env as fallback (for some build configurations)
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || (typeof process !== 'undefined' && process.env?.VITE_SUPABASE_URL);
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || (typeof process !== 'undefined' && process.env?.VITE_SUPABASE_ANON_KEY);

// Debug logging removed for production

// Check if we have valid Supabase credentials
const hasValidSupabaseConfig = SUPABASE_URL && 
  SUPABASE_ANON_KEY && 
  SUPABASE_URL !== 'placeholder' && 
  SUPABASE_ANON_KEY !== 'placeholder' &&
  SUPABASE_URL.startsWith('http');

// Create a mock client if Supabase is not configured
const createMockClient = () => {
  console.warn('Supabase not configured. Using mock client.');
  return {
    auth: {
      signInWithPassword: async () => ({ error: { message: 'Supabase not configured' } }),
      signUp: async () => ({ error: { message: 'Supabase not configured' } }),
      signOut: async () => ({ error: { message: 'Supabase not configured' } }),
      getSession: async () => ({ data: { session: null }, error: null }),
      onAuthStateChange: () => ({ data: { subscription: null } }),
    },
    from: () => ({
      select: () => ({ data: [], error: null }),
      insert: () => ({ data: null, error: { message: 'Supabase not configured' } }),
      update: () => ({ data: null, error: { message: 'Supabase not configured' } }),
      delete: () => ({ data: null, error: { message: 'Supabase not configured' } }),
    }),
    functions: {
      invoke: async (functionName: string, options?: { body?: any }) => {
        console.error(`Supabase functions not available. Attempted to invoke: ${functionName}`);
        return {
          data: null,
          error: {
            message: 'Supabase not configured. Please set VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY environment variables.',
            details: 'The Supabase client is using a mock client because environment variables are not set.'
          }
        };
      },
    },
  } as any;
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = hasValidSupabaseConfig 
  ? createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
      auth: {
        // All three need browser storage. During static generation there is no
        // session to persist and no URL to inspect, so they are switched off
        // rather than left to fail.
        autoRefreshToken: IS_BROWSER,
        persistSession: IS_BROWSER,
        detectSessionInUrl: IS_BROWSER,
        flowType: 'pkce', // Use PKCE flow for better security
      },
      global: {
        headers: {
          'X-Client-Info': 'real-estate-website',
        },
      },
    })
  : createMockClient();

// Add error handling wrapper
export const safeSupabase = {
  ...supabase,
  auth: {
    ...supabase.auth,
    signInWithPassword: async (credentials: { email: string; password: string }) => {
      try {
        return await supabase.auth.signInWithPassword(credentials);
      } catch (error) {
        console.error('Authentication error:', error);
        throw new Error('Authentication failed. Please try again.');
      }
    },
    signUp: async (credentials: { email: string; password: string }) => {
      try {
        return await supabase.auth.signUp(credentials);
      } catch (error) {
        console.error('Signup error:', error);
        throw new Error('Signup failed. Please try again.');
      }
    },
  },
};